version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: "pg"
    ports:
      - "54320:5432"

    environment:
      POSTGRES_PASSWORD: example

    volumes:
      - ./db/data:/var/lib/postgresql/data