version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    container_name: "db"
    ports:
      - "54320:5432"
    expose: 
      - "54320"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    container_name: "web"
    command: sh -c "npm run migrate && node photoServer.js /Users/jkuruvilla/jimmy/photoSite/share"
    volumes:
      - .:/usr/app/
      - ./share:/Users/jkuruvilla/jimmy/photoSite/share
    ports:
      - "4000:4000"
    environment:
      DOCKERDB: 1
    depends_on:
      - db



    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 15