# /Users/jkuruvilla/jimmy/photoSite/share
# /mnt/backup/share/Photos
version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    container_name: "db"
    ports:
      - "54320:5432"
    expose: 
      - "54320"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /mnt/data/photoDb:/var/lib/postgresql/data
    user: 1000:1001
